/* ============================================================
   Word Fall — word bank (~1000+ common English words)

   One flat array; script.js buckets it into difficulty tiers
   by word length at load time (3–5 easy, 6–9 medium, 10+ hard).
   Lowercase a–z only — lock-on typing matches single letter keys,
   so no spaces, hyphens, or apostrophes.

   Grouped by length, alphabetical within each group.
   ============================================================ */

"use strict";

const WORD_BANK = [
  // ---- 3 letters ----
  "act", "add", "age", "air", "ant", "arm", "art", "ash", "ask", "bag",
  "bat", "bed", "bee", "big", "box", "boy", "bug", "bus", "buy", "cab",
  "cap", "car", "cat", "cow", "cry", "cup", "cut", "day", "den", "dig",
  "dip", "dog", "dot", "dry", "ear", "eat", "egg", "elf", "end", "eye",
  "fan", "far", "fig", "fin", "fit", "fix", "fly", "fog", "fox", "fun",
  "fur", "gap", "gas", "gem", "get", "gum", "guy", "ham", "hat", "hen",
  "hit", "hop", "hot", "hub", "hug", "hut", "ice", "ink", "jam", "jar",
  "jaw", "jet", "job", "jog", "joy", "jug", "key", "kid", "kit", "lab",
  "lap", "law", "leg", "lid", "lip", "log", "low", "mad", "man", "map",
  "mat", "mix", "mob", "mop", "mud", "mug", "nap", "net", "new", "nod",
  "now", "nut", "oak", "oar", "odd", "oil", "old", "one", "owl", "own",
  "pad", "pan", "paw", "pay", "pea", "pen", "pet", "pie", "pig", "pin",
  "pit", "pod", "pop", "pot", "pub", "pup", "put", "rag", "ram", "rat",
  "raw", "ray", "red", "rib", "rid", "rim", "rip", "rob", "rod", "rot",
  "row", "rub", "rug", "run", "sad", "saw", "sea", "set", "shy", "sip",
  "sit", "six", "ski", "sky", "sly", "sob", "son", "spa", "spy", "sum",
  "sun", "tab", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "tie",
  "tin", "tip", "toe", "top", "tow", "toy", "try", "tub", "tug", "van",
  "vet", "vow", "wag", "war", "wax", "way", "web", "wet", "wig", "win",
  "wok", "yak", "yam", "zip", "zoo",

  // ---- 4 letters ----
  "able", "acid", "aunt", "away", "baby", "back", "bake", "ball", "band", "bank",
  "barn", "base", "bath", "bead", "beam", "bean", "bear", "beat", "bell", "belt",
  "bend", "bird", "bite", "blue", "boat", "bold", "bolt", "bone", "book", "boot",
  "born", "bowl", "bulb", "bull", "bump", "burn", "bush", "busy", "cake", "calf",
  "call", "calm", "camp", "cape", "card", "care", "cart", "case", "cash", "cast",
  "cave", "cell", "chat", "chef", "chin", "chip", "city", "clap", "claw", "clay",
  "clip", "club", "coal", "coat", "code", "coil", "coin", "cold", "comb", "cook",
  "cool", "copy", "cord", "core", "corn", "cost", "cozy", "crab", "crew", "crop",
  "crow", "cube", "curb", "cure", "curl", "dare", "dark", "dart", "dash", "date",
  "dawn", "deal", "dear", "debt", "deck", "deep", "deer", "dent", "desk", "dial",
  "dice", "diet", "dirt", "dish", "dive", "dock", "doll", "dome", "door", "dose",
  "down", "drag", "draw", "drip", "drop", "drum", "duck", "dull", "dust", "duty",
  "each", "earn", "east", "easy", "edge", "exit", "face", "fact", "fade", "fail",
  "fair", "fall", "fame", "farm", "fast", "fear", "feed", "feel", "fern", "file",
  "fill", "film", "find", "fine", "fire", "firm", "fish", "fist", "five", "flag",
  "flat", "flip", "flow", "foam", "fold", "folk", "food", "foot", "fork", "form",
  "fort", "four", "free", "frog", "fuel", "full", "fund", "gain", "game", "gate",
  "gaze", "gear", "gift", "girl", "give", "glad", "glow", "glue", "goal", "goat",
  "gold", "golf", "good", "gown", "grab", "gray", "grid", "grin", "grip", "grow",
  "gulf", "hail", "hair", "half", "hall", "hand", "hang", "hard", "harm", "hawk",
  "heal", "heap", "hear", "heat", "heel", "help", "herb", "herd", "hero", "hide",
  "high", "hike", "hill", "hint", "hire", "hold", "hole", "home", "hook", "hope",
  "horn", "hose", "host", "hour", "huge", "hunt", "hurt", "idea", "inch", "iron",
  "item", "jazz", "join", "joke", "jump", "junk", "jury", "keen", "keep", "kick",
  "kind", "king", "kiss", "kite", "knee", "knit", "knob", "knot", "lace", "lack",
  "lake", "lamb", "lamp", "land", "lane", "last", "late", "lawn", "lazy", "leaf",
  "lean", "leap", "left", "lend", "lens", "life", "lift", "like", "lime", "line",
  "link", "lion", "list", "live", "load", "loaf", "loan", "lock", "loft", "long",
  "look", "loop", "lord", "lose", "loss", "loud", "love", "luck", "lung", "maid",
  "mail", "main", "make", "mall", "mask", "mast", "meal", "meat", "melt", "mesh",
  "mild", "mile", "milk", "mill", "mind", "mine", "mint", "miss", "mist", "mode",
  "mold", "monk", "mood", "moon", "moss", "moth", "move", "mule", "myth", "nail",
  "name", "navy", "near", "neat", "neck", "need", "nest", "news", "nice", "nine",
  "noon", "nose", "note", "noun", "oath", "obey", "once", "only", "open", "oval",
  "oven", "over", "pace", "pack", "page", "pail", "pain", "pair", "pale", "palm",
  "park", "part", "pass", "past", "path", "pave", "peak", "pear", "peel", "pile",
  "pine", "pink", "pipe", "plan", "play", "plot", "plow", "plug", "plum", "poem",
  "poet", "pole", "pond", "pony", "pool", "port", "pose", "post", "pour", "pray",
  "pull", "pump", "pure", "push", "quiz", "race", "rack", "rage", "rail", "rain",
  "rake", "rank", "rare", "rate", "read", "real", "rear", "rent", "rest", "rice",
  "rich", "ride", "ring", "ripe", "rise", "risk", "road", "roam", "roar", "robe",
  "rock", "role", "roll", "roof", "room", "root", "rope", "rose", "ruby", "rude",
  "ruin", "rule", "rush", "rust", "safe", "sage", "sail", "salt", "sand", "save",
  "scan", "seal", "seat", "seed", "seek", "sell", "send", "ship", "shoe", "shop",
  "shot", "show", "shut", "sick", "side", "sign", "silk", "sing", "sink", "site",
  "size", "skin", "sled", "slim", "slip", "slow", "snap", "snow", "soap", "sock",
  "sofa", "soft", "soil", "sole", "song", "soon", "sort", "soup", "sour", "span",
  "spin", "spot", "star", "stay", "stem", "step", "stew", "stir", "stop", "suit",
  "sure", "swan", "swap", "swim", "tail", "take", "tale", "talk", "tall", "tame",
  "tank", "tape", "task", "team", "tear", "tell", "tend", "tent", "test", "text",
  "thin", "tide", "tile", "time", "tiny", "toad", "toll", "tone", "tool", "torn",
  "toss", "tour", "town", "trap", "tray", "tree", "trim", "trip", "true", "tube",
  "tuck", "tune", "turn", "twin", "type", "ugly", "unit", "upon", "urge", "user",
  "vain", "vase", "vast", "veil", "vein", "vest", "view", "vine", "vote", "wade",
  "wage", "wait", "wake", "walk", "wall", "wand", "want", "warm", "warn", "wash",
  "wave", "weak", "wear", "week", "well", "west", "whip", "wide", "wife", "wild",
  "will", "wind", "wine", "wing", "wink", "wipe", "wire", "wise", "wish", "wolf",
  "wood", "wool", "word", "work", "worm", "wrap", "yard", "yarn", "yawn", "year",
  "yell", "zero", "zone",

  // ---- 5 letters ----
  "about", "above", "actor", "admit", "adopt", "adult", "after", "again", "agent", "agree",
  "ahead", "alarm", "album", "alert", "alike", "alive", "alley", "allow", "alone", "along",
  "aloud", "amber", "angel", "anger", "angle", "ankle", "apart", "apple", "apply", "apron",
  "arena", "argue", "arise", "armor", "arrow", "aside", "audio", "avoid", "awake", "award",
  "aware", "badge", "baker", "basic", "basin", "batch", "beach", "beard", "beast", "begin",
  "belly", "below", "bench", "berry", "birth", "black", "blade", "blame", "blank", "blast",
  "blaze", "blend", "bless", "blind", "block", "bloom", "board", "boast", "bonus", "boost",
  "booth", "bound", "brain", "brake", "brand", "brave", "bread", "break", "brick", "bride",
  "brief", "bring", "broad", "broke", "brook", "broom", "brown", "brush", "build", "built",
  "bunch", "burst", "cabin", "cable", "camel", "candy", "canoe", "cargo", "carry", "carve",
  "catch", "cause", "chain", "chair", "chalk", "charm", "chart", "chase", "cheap", "check",
  "cheer", "chess", "chest", "chief", "child", "chill", "choir", "civil", "claim", "clash",
  "class", "clean", "clear", "clerk", "click", "cliff", "climb", "cloak", "clock", "close",
  "cloth", "cloud", "coach", "coast", "cobra", "cocoa", "color", "comet", "comic", "coral",
  "couch", "cough", "count", "court", "cover", "crack", "craft", "crane", "crash", "crawl",
  "crazy", "cream", "creek", "crime", "crisp", "cross", "crowd", "crown", "crumb", "crush",
  "curve", "cycle", "daily", "dairy", "dance", "decay", "delay", "dense", "depth", "devil",
  "diary", "dirty", "ditch", "dodge", "donor", "doubt", "dozen", "draft", "drain", "drama",
  "dream", "dress", "drift", "drill", "drink", "drive", "dusty", "eager", "eagle", "early",
  "earth", "eight", "elbow", "elder", "empty", "enemy", "enjoy", "enter", "entry", "equal",
  "error", "essay", "event", "every", "exact", "exist", "extra", "fable", "faint", "fairy",
  "faith", "false", "fancy", "fault", "favor", "feast", "fence", "ferry", "fever", "fiber",
  "field", "fifth", "fifty", "fight", "final", "first", "flame", "flash", "fleet", "flesh",
  "float", "flock", "flood", "floor", "flour", "fluid", "flute", "focus", "force", "forge",
  "forth", "forty", "found", "frame", "fresh", "front", "frost", "fruit", "funny", "gauge",
  "ghost", "giant", "given", "glass", "gleam", "glide", "globe", "glory", "glove", "going",
  "goose", "grace", "grade", "grain", "grand", "grant", "grape", "grasp", "grass", "grave",
  "graze", "great", "green", "greet", "grief", "grill", "grind", "group", "grove", "growl",
  "guard", "guess", "guest", "guide", "habit", "happy", "harsh", "hatch", "heart", "heavy",
  "hedge", "hello", "hence", "hobby", "honey", "honor", "horse", "hotel", "house", "human",
  "humor", "hurry", "ideal", "image", "index", "inner", "input", "issue", "ivory", "jelly",
  "jewel", "joint", "jolly", "judge", "juice", "knife", "knock", "label", "labor", "large",
  "laser", "latch", "laugh", "layer", "learn", "lease", "least", "leave", "legal", "lemon",
  "level", "light", "limit", "linen", "liver", "lobby", "local", "lodge", "logic", "loose",
  "loyal", "lucky", "lunar", "lunch", "magic", "major", "maple", "march", "match", "maybe",
  "mayor", "medal", "media", "mercy", "merge", "merit", "merry", "metal", "meter", "might",
  "minor", "minus", "mixer", "model", "moist", "money", "month", "moral", "motor", "mount",
  "mouse", "mouth", "movie", "music", "nasty", "nerve", "never", "newly", "night", "noble",
  "noise", "north", "notch", "novel", "nurse", "ocean", "offer", "often", "olive", "onion",
  "orbit", "order", "organ", "other", "otter", "ounce", "outer", "owner", "ozone", "paint",
  "panel", "panic", "paper", "party", "pasta", "paste", "patch", "pause", "peace", "peach",
  "pearl", "pedal", "penny", "perch", "petal", "phase", "phone", "photo", "piano", "piece",
  "pilot", "pinch", "pitch", "pivot", "pixel", "pizza", "place", "plain", "plane", "plant",
  "plate", "plaza", "plead", "point", "polar", "porch", "pouch", "pound", "power", "press",
  "price", "pride", "prime", "print", "prize", "proof", "proud", "prove", "prune", "pulse",
  "punch", "pupil", "puppy", "purse", "queen", "query", "quest", "queue", "quick", "quiet",
  "quilt", "quote", "radar", "radio", "raise", "rally", "ranch", "range", "rapid", "ratio",
  "reach", "react", "ready", "realm", "rebel", "reign", "relax", "relay", "reply", "rhyme",
  "rider", "ridge", "rifle", "right", "rigid", "rinse", "risky", "rival", "river", "roast",
  "robin", "robot", "rocky", "rough", "round", "route", "royal", "ruler", "rumor", "rural",
  "saint", "salad", "sauce", "scale", "scare", "scarf", "scene", "scent", "scoop", "scope",
  "score", "scout", "scrap", "screw", "seize", "sense", "serve", "seven", "shade", "shaft",
  "shake", "shame", "shape", "share", "sharp", "sheep", "sheet", "shelf", "shell", "shift",
  "shine", "shiny", "shirt", "shock", "shoot", "shore", "short", "shout", "shown", "sight",
  "silly", "since", "siren", "sixty", "skate", "skill", "skirt", "slate", "sleep", "slice",
  "slide", "slope", "small", "smart", "smell", "smile", "smoke", "snack", "snail", "snake",
  "sneak", "solar", "solid", "solve", "sonic", "sorry", "sound", "south", "space", "spare",
  "spark", "speak", "speed", "spell", "spend", "spice", "spike", "spill", "spine", "spoil",
  "spoon", "sport", "spray", "staff", "stage", "stain", "stair", "stake", "stale", "stamp",
  "stand", "stare", "start", "state", "steam", "steel", "steep", "steer", "stick", "stiff",
  "still", "sting", "stock", "stone", "stool", "store", "storm", "story", "stove", "strap",
  "straw", "strip", "stuck", "study", "stuff", "stump", "style", "sugar", "suite", "sunny",
  "super", "surge", "swamp", "sweep", "sweet", "swift", "swing", "sword", "syrup", "table",
  "taken", "taste", "teach", "tempo", "tenth", "thank", "theft", "theme", "there", "thick",
  "thief", "thing", "think", "third", "three", "throw", "thumb", "tiger", "tight", "timer",
  "title", "toast", "today", "token", "tooth", "topic", "torch", "total", "touch", "tough",
  "towel", "tower", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash",
  "treat", "trend", "trial", "tribe", "trick", "troop", "truck", "trunk", "trust", "truth",
  "tulip", "tutor", "twice", "twist", "uncle", "under", "union", "unite", "unity", "until",
  "upper", "upset", "urban", "usage", "usual", "valid", "value", "valve", "vapor", "vault",
  "verse", "video", "villa", "vinyl", "virus", "visit", "vital", "vivid", "vocal", "voice",
  "vowel", "wagon", "waist", "watch", "water", "weary", "weave", "wedge", "whale", "wheat",
  "wheel", "where", "which", "while", "white", "whole", "widow", "width", "windy", "witch",
  "woman", "world", "worry", "worth", "wound", "wrist", "write", "wrong", "yacht", "yeast",
  "yield", "young", "youth", "zebra",

  // ---- 6 letters ----
  "anchor", "animal", "annual", "answer", "appear", "arrive", "artist", "august", "autumn", "avenue",
  "backup", "bakery", "banana", "banner", "barrel", "basket", "battle", "beauty", "become", "before",
  "behind", "belief", "better", "beyond", "bishop", "bitter", "bottle", "bounce", "branch", "breath",
  "breeze", "bridge", "bright", "bronze", "bubble", "bucket", "budget", "bullet", "bundle", "burden",
  "butter", "button", "camera", "campus", "candle", "cannon", "canvas", "carbon", "career", "carpet",
  "carrot", "castle", "casual", "cattle", "caught", "cellar", "cement", "center", "cereal", "change",
  "chapel", "charge", "cherry", "choice", "choose", "chorus", "church", "circle", "circus", "clever",
  "client", "closet", "clumsy", "coffee", "collar", "column", "combat", "comedy", "common", "copper",
  "corner", "cotton", "county", "couple", "course", "cousin", "coyote", "cradle", "crayon", "create",
  "credit", "crisis", "critic", "crunch", "custom", "dagger", "damage", "danger", "dazzle", "debate",
  "decade", "decide", "defeat", "defend", "define", "degree", "demand", "deputy", "desert", "design",
  "desire", "detail", "device", "dinner", "divide", "doctor", "dollar", "domain", "donkey", "double",
  "dragon", "drawer", "easily", "eleven", "emerge", "empire", "employ", "enable", "energy", "engine",
  "enough", "entire", "escape", "estate", "exceed", "except", "excite", "excuse", "expand", "expect",
  "expert", "export", "extend", "fabric", "falcon", "family", "famous", "farmer", "faucet", "fellow",
  "female", "fierce", "figure", "filter", "finger", "finish", "flavor", "flight", "flower", "follow",
  "forest", "forget", "formal", "format", "fossil", "foster", "fourth", "freeze", "friend", "frozen",
  "future", "galaxy", "garage", "garden", "gather", "gentle", "giggle", "ginger", "glance", "global",
  "goblet", "golden", "gospel", "gossip", "ground", "growth", "guitar", "hammer", "handle", "happen",
  "harbor", "hardly", "hazard", "health", "heaven", "height", "helmet", "hidden", "hollow", "honest",
  "horror", "hunger", "hunter", "iguana", "impact", "import", "income", "indeed", "indoor", "infant",
  "inform", "injury", "insect", "inside", "intent", "invent", "invest", "island", "jacket", "jungle",
  "junior", "kettle", "kidney", "kitten", "ladder", "lagoon", "laptop", "launch", "lawyer", "leader",
  "legacy", "legend", "length", "lesson", "letter", "likely", "liquid", "listen", "little", "lively",
  "lizard", "locker", "lonely", "lounge", "lumber", "luxury", "magnet", "mammal", "manage", "manner",
  "marble", "margin", "marine", "market", "master", "matter", "meadow", "medium", "member", "memory",
  "mentor", "merely", "method", "middle", "mighty", "mirror", "mobile", "modern", "module", "moment",
  "monkey", "mosaic", "mostly", "mother", "motion", "muffin", "murmur", "muscle", "museum", "mutual",
  "myself", "napkin", "narrow", "nation", "native", "nature", "nearby", "nearly", "nectar", "needle",
  "nephew", "nickel", "nobody", "normal", "notice", "number", "nugget", "object", "obtain", "occupy",
  "office", "offset", "online", "option", "orange", "orchid", "origin", "outfit", "output", "oyster",
  "palace", "pantry", "parade", "parent", "parrot", "pastel", "pastry", "patent", "patrol", "pebble",
  "pencil", "people", "pepper", "period", "permit", "person", "pickle", "picnic", "pigeon", "pillow",
  "pirate", "pistol", "planet", "plenty", "pocket", "poetry", "police", "policy", "polish", "pollen",
  "ponder", "portal", "poster", "potato", "powder", "praise", "prayer", "prefer", "pretty", "prince",
  "prison", "profit", "prompt", "proper", "public", "puddle", "puppet", "purple", "pursue", "puzzle",
  "rabbit", "racket", "radish", "raffle", "random", "rather", "reason", "recent", "recipe", "record",
  "reduce", "reform", "refuse", "region", "relate", "remain", "remark", "remedy", "remind", "remote",
  "repair", "repeat", "report", "rescue", "resort", "result", "retail", "retire", "return", "reveal",
  "reward", "rhythm", "ribbon", "riddle", "ripple", "ritual", "rocket", "rotate", "rubber", "rustic",
  "sacred", "saddle", "safari", "safety", "salmon", "sample", "scheme", "school", "scream", "screen",
  "script", "search", "season", "second", "secret", "sector", "secure", "seldom", "select", "senior",
  "series", "sermon", "settle", "severe", "shadow", "shaker", "shovel", "shower", "shrine", "shrink",
  "signal", "silent", "silver", "simple", "singer", "single", "sister", "sketch", "slight", "slogan",
  "smooth", "soccer", "socket", "sodium", "sphere", "spider", "spirit", "splash", "sponge", "spread",
  "spring", "sprint", "square", "squash", "stable", "statue", "steady", "sticky", "stormy", "strain",
  "strand", "stream", "street", "stress", "strike", "string", "stroke", "strong", "studio", "submit",
  "subtle", "suburb", "sudden", "summer", "summit", "sunset", "supper", "supply", "surely", "survey",
  "switch", "symbol", "system", "tackle", "tailor", "talent", "target", "tavern", "temple", "tender",
  "tennis", "theory", "thirty", "thread", "thrive", "throne", "ticket", "timber", "tissue", "toffee",
  "tomato", "tongue", "trauma", "travel", "treaty", "tremor", "trophy", "tunnel", "turkey", "turtle",
  "twelve", "twenty", "unfair", "unique", "unless", "unlike", "update", "upload", "urgent", "useful",
  "vacuum", "valley", "velvet", "vendor", "verify", "vessel", "victim", "violet", "violin", "virtue",
  "vision", "visual", "volume", "voyage", "waffle", "walnut", "wander", "wealth", "weapon", "weekly",
  "weight", "window", "winner", "winter", "wisdom", "wizard", "wonder", "wooden", "worker", "writer",
  "yellow", "yogurt", "zodiac",

  // ---- 7 letters ----
  "ability", "absence", "academy", "account", "achieve", "address", "advance", "airport", "amazing", "ancient",
  "antenna", "anxiety", "apology", "aquatic", "archery", "arrange", "article", "athlete", "attempt", "auction",
  "average", "balance", "balcony", "balloon", "bargain", "battery", "bedroom", "believe", "benefit", "bicycle",
  "biology", "blanket", "blossom", "bravery", "brother", "cabbage", "cabinet", "caption", "capture", "caravan",
  "careful", "carrier", "caution", "ceiling", "century", "certain", "chamber", "channel", "chapter", "charity",
  "chicken", "chimney", "citizen", "clarity", "climate", "clothes", "collect", "college", "combine", "comfort",
  "command", "comment", "company", "compare", "compass", "complex", "compose", "concept", "concert", "conduct",
  "confirm", "connect", "consist", "contain", "content", "contest", "context", "control", "convert", "cooking",
  "correct", "cottage", "council", "country", "courage", "cricket", "crucial", "crystal", "culture", "curious",
  "current", "curtain", "cushion", "decline", "default", "defense", "deliver", "density", "deposit", "desktop",
  "despite", "dessert", "destiny", "develop", "diagram", "diamond", "dignity", "discuss", "display", "dispute",
  "distant", "diverse", "dolphin", "drawing", "dungeon", "eastern", "economy", "edition", "elegant", "element",
  "elevate", "embrace", "emotion", "emperor", "enhance", "episode", "equator", "essence", "eternal", "evening",
  "exactly", "examine", "example", "excited", "exhibit", "expense", "explain", "explore", "express", "extreme",
  "factory", "faculty", "failure", "fantasy", "fashion", "feather", "feature", "federal", "fiction", "fifteen",
  "finance", "fitness", "foreign", "forever", "formula", "fortune", "forward", "freedom", "freight", "gallery",
  "garbage", "general", "genuine", "gesture", "glacier", "glimpse", "grammar", "gravity", "grocery", "habitat",
  "hallway", "hamster", "harmony", "harvest", "healthy", "hearing", "highway", "history", "holiday", "horizon",
  "however", "hundred", "hunting", "husband", "iceberg", "imagine", "improve", "include", "initial", "inquiry",
  "insight", "inspire", "instant", "install", "intense", "involve", "journal", "journey", "justice", "justify",
  "kingdom", "kitchen", "lantern", "lasting", "laundry", "lawsuit", "leather", "lecture", "leisure", "liberty",
  "library", "license", "lightly", "limited", "lobster", "logical", "loyalty", "machine", "magical", "manager",
  "mansion", "mariner", "maximum", "meaning", "measure", "medical", "meeting", "mention", "message", "mineral",
  "minimum", "miracle", "mission", "mistake", "mixture", "monitor", "monster", "morning", "musical", "mystery",
  "natural", "neither", "nervous", "network", "nothing", "nowhere", "nuclear", "obvious", "october", "officer",
  "opening", "operate", "opinion", "organic", "outcome", "outdoor", "outside", "overall", "pacific", "package",
  "painter", "pancake", "parking", "partner", "passage", "passion", "patient", "pattern", "payment", "penalty",
  "pending", "perfect", "perform", "perhaps", "persist", "picture", "pioneer", "plastic", "plumber", "pointer",
  "popular", "portion", "poverty", "precise", "predict", "premium", "prepare", "present", "prevent", "primary",
  "printer", "privacy", "private", "problem", "process", "produce", "product", "profile", "program", "project",
  "promise", "promote", "protect", "protein", "provide", "publish", "pumpkin", "purpose", "pyramid", "quality",
  "quarter", "radical", "rainbow", "readily", "reality", "realize", "receive", "recover", "reflect", "refresh",
  "regular", "related", "release", "remains", "replace", "request", "require", "reserve", "resolve", "respect",
  "respond", "restore", "revenue", "reverse", "routine", "running", "satisfy", "sausage", "science", "scratch",
  "section", "serious", "service", "session", "seventy", "several", "shampoo", "shelter", "sixteen", "society",
  "soldier", "somehow", "speaker", "special", "sponsor", "stadium", "station", "storage", "strange", "stretch",
  "student", "subject", "succeed", "success", "suggest", "support", "suppose", "supreme", "surface", "surgeon",
  "surplus", "survive", "suspect", "sustain", "sweater", "teacher", "theater", "therapy", "thought", "thunder",
  "tonight", "totally", "tourism", "towards", "traffic", "trailer", "trouble", "typical", "uniform", "unknown",
  "upgrade", "usually", "utility", "vanilla", "variety", "vehicle", "venture", "version", "veteran", "victory",
  "village", "vintage", "visible", "visitor", "voltage", "volcano", "warrior", "weather", "website", "welcome",
  "western", "whisper", "willing", "witness", "wrestle", "writing",

  // ---- 8 letters ----
  "absolute", "abstract", "academic", "accident", "accurate", "activity", "actually", "addition", "adequate", "advocate",
  "aircraft", "although", "aluminum", "announce", "annually", "anywhere", "apparent", "appetite", "approach", "approval",
  "argument", "artistic", "assembly", "athletic", "attitude", "audience", "bachelor", "bacteria", "baseball", "bathroom",
  "birthday", "blizzard", "boundary", "building", "bulletin", "business", "calendar", "campaign", "capacity", "carnival",
  "category", "cautious", "ceremony", "chemical", "children", "cinnamon", "commerce", "complete", "compound", "computer",
  "conclude", "concrete", "conflict", "confused", "congress", "consider", "constant", "consumer", "continue", "contract",
  "contrast", "convince", "corridor", "courtesy", "creative", "creature", "critical", "cucumber", "cultural", "currency",
  "customer", "database", "daughter", "daylight", "deadline", "december", "decision", "decrease", "dedicate", "delicate",
  "delivery", "describe", "designer", "detailed", "dialogue", "diameter", "dinosaur", "directly", "director", "disaster",
  "discount", "discover", "disorder", "distance", "division", "document", "domestic", "dominant", "doorstep", "doubtful",
  "download", "dramatic", "duration", "eighteen", "election", "electric", "elephant", "elevator", "eligible", "emphasis",
  "employee", "engineer", "enormous", "entrance", "envelope", "estimate", "everyone", "evidence", "exchange", "exciting",
  "exercise", "explicit", "exposure", "external", "facility", "familiar", "favorite", "feedback", "festival", "flexible",
  "football", "forecast", "fourteen", "fraction", "frequent", "friendly", "frontier", "function", "generate", "generous",
  "graduate", "graphics", "grateful", "guardian", "handbook", "hardware", "headline", "heritage", "highland", "historic",
  "homework", "horrible", "hospital", "humanity", "identify", "identity", "incident", "increase", "indicate", "industry",
  "infinite", "informal", "instance", "interior", "internal", "interval", "intimate", "isolated", "judgment", "keyboard",
  "language", "laughter", "lavender", "learning", "leverage", "lifetime", "likewise", "literacy", "location", "magazine",
  "magnetic", "maintain", "majority", "marathon", "marriage", "material", "maturity", "meantime", "mechanic", "medicine",
  "memorial", "merchant", "midnight", "military", "minister", "minority", "moderate", "molecule", "momentum", "monument",
  "moreover", "mortgage", "mountain", "movement", "multiple", "mushroom", "national", "negative", "neighbor", "nineteen",
  "northern", "notebook", "november", "numerous", "obstacle", "occasion", "offering", "official", "operator", "opponent",
  "opposite", "optimism", "ordinary", "organism", "original", "ornament", "overcome", "overhead", "overseas", "painting",
  "paradise", "parallel", "particle", "passport", "peaceful", "pentagon", "personal", "persuade", "physical", "pipeline",
  "platform", "pleasant", "politics", "porridge", "portrait", "position", "positive", "possible", "powerful", "practice",
  "precious", "pregnant", "presence", "preserve", "pressure", "previous", "princess", "priority", "probable", "proposal",
  "protocol", "province", "purchase", "quantity", "question", "reaction", "receiver", "regional", "register", "relative",
  "relevant", "reliable", "religion", "remember", "reporter", "republic", "research", "resource", "response", "revision",
  "romantic", "sandwich", "scenario", "schedule", "scissors", "seasonal", "security", "sentence", "separate", "sequence",
  "shortage", "shoulder", "simulate", "skeleton", "slippery", "software", "solution", "southern", "specific", "spectrum",
  "standard", "strategy", "strength", "struggle", "stunning", "suburban", "sunlight", "sunshine", "surprise", "survival",
  "symbolic", "sympathy", "taxation", "teamwork", "teenager", "terminal", "terrible", "thirteen", "thousand", "together",
  "tomorrow", "training", "transfer", "treasure", "triangle", "tropical", "ultimate", "umbrella", "universe", "upstairs",
  "vacation", "valuable", "variable", "vertical", "violence", "volcanic", "warranty", "weakness", "whatever", "wildlife",
  "wireless", "withdraw", "workshop", "yourself",

  // ---- 9 letters ----
  "adventure", "advertise", "afternoon", "agreement", "algorithm", "ambitious", "amusement", "apartment", "appliance", "associate",
  "astronaut", "attention", "attribute", "authority", "automatic", "awareness", "beautiful", "beginning", "behavior", "blueprint",
  "boulevard", "breakfast", "brilliant", "broadcast", "bulldozer", "butterfly", "calculate", "candidate", "cathedral", "celebrate",
  "challenge", "character", "chemistry", "childhood", "chocolate", "classroom", "colleague", "commander", "community", "companion",
  "component", "condition", "confident", "confusion", "conscious", "construct", "container", "continent", "corporate", "courtroom",
  "criterion", "crocodile", "crossword", "curiosity", "customary", "dandelion", "dangerous", "dashboard", "dedicated", "defensive",
  "delicious", "departure", "desperate", "detective", "determine", "devastate", "diagnosis", "different", "difficult", "dimension",
  "direction", "directory", "disappear", "discovery", "education", "effective", "efficient", "elaborate", "elsewhere", "emergency",
  "emphasize", "encounter", "enjoyable", "essential", "establish", "evolution", "excellent", "exception", "executive", "existence",
  "expansion", "expensive", "explosion", "extension", "extensive", "fantastic", "fascinate", "fisherman", "following", "footprint",
  "framework", "frequency", "furniture", "generally", "gentleman", "geography", "gymnasium", "happiness", "hamburger", "highlight",
  "historian", "household", "hurricane", "identical", "immediate", "important", "influence", "innocence", "insurance", "intention",
  "interview", "introduce", "invention", "jellyfish", "knowledge", "landscape", "lifestyle", "lightning", "limestone", "logistics",
  "machinery", "magnitude", "marketing", "marvelous", "meanwhile", "mechanism", "messenger", "milestone", "narrative", "necessary",
  "newspaper", "nightmare", "northeast", "nutrition", "objective", "obviously", "offensive", "operation", "orchestra", "organizer",
  "otherwise", "ourselves", "overnight", "paragraph", "partition", "passenger", "perfectly", "permanent", "personnel", "physician",
  "pineapple", "pollution", "porcelain", "potential", "precisely", "president", "primarily", "principal", "principle", "privilege",
  "procedure", "professor", "promotion", "provision", "publisher", "quotation", "radiation", "raspberry", "recognize", "recording",
  "rectangle", "reduction", "redundant", "reference", "rehearsal", "remainder", "represent", "residence", "satellite", "scientist",
  "secondary", "secretary", "selection", "semicolon", "sensation", "september", "seventeen", "signature", "situation", "snowflake",
  "sometimes", "somewhere", "spaghetti", "spectacle", "statement", "steadfast", "strategic", "streaming", "structure", "substance",
  "supervise", "surrender", "technique", "telephone", "telescope", "temporary", "territory", "testimony", "therefore", "threshold",
  "timetable", "tolerance", "tradition", "translate", "transport", "treatment", "twentieth", "underline", "undertake", "unhealthy",
  "universal", "vegetable", "vibration", "violation", "virtually", "visionary", "volunteer", "warehouse", "waterfall", "wonderful",
  "workforce", "workplace", "worldwide", "yesterday",

  // ---- 10+ letters ----
  "absolutely", "accomplish", "achievement", "acquisition", "adventurous", "agriculture", "alphabetical", "ambassador", "appreciation", "arrangement",
  "association", "atmosphere", "attraction", "automobile", "background", "basketball", "calculator", "celebration", "cheesecake", "chimpanzee",
  "civilization", "collection", "combination", "comfortable", "commercial", "commitment", "communication", "comparison", "competition", "completely",
  "complicated", "concentrate", "conclusion", "confidence", "connection", "consequence", "conservation", "considerable", "constitution", "construction",
  "consultant", "contribution", "convenient", "conversation", "cooperation", "coordination", "corporation", "creativity", "curriculum", "decoration",
  "dedication", "definition", "democratic", "department", "depression", "description", "destination", "determination", "development", "dictionary",
  "difference", "difficulty", "disappoint", "discipline", "discussion", "distribution", "earthquake", "efficiency", "electricity", "elementary",
  "encyclopedia", "engagement", "engineering", "enthusiasm", "environment", "evaluation", "everything", "examination", "excellence", "excitement",
  "exhibition", "expedition", "experience", "experiment", "explanation", "expression", "extraordinary", "fascinating", "federation", "fingerprint",
  "firefighter", "flashlight", "foundation", "friendship", "frustration", "fundamental", "generation", "government", "grandfather", "grandmother",
  "grasshopper", "handwriting", "headquarters", "helicopter", "hippopotamus", "horizontal", "hospitality", "illustration", "imagination", "immediately",
  "importance", "impression", "incredible", "independent", "industrial", "information", "infrastructure", "ingredient", "inspection", "instrument",
  "intelligence", "interesting", "international", "introduction", "investigate", "invitation", "journalist", "laboratory", "leadership", "legislation",
  "lighthouse", "limitation", "literature", "locomotive", "magnificent", "maintenance", "management", "marketplace", "mathematics", "measurement",
  "medication", "membership", "microphone", "microscope", "motorcycle", "mysterious", "navigation", "negotiation", "neighborhood", "newsletter",
  "nomination", "observation", "occupation", "opportunity", "organization", "particular", "partnership", "passionate", "percentage", "perception",
  "performance", "permission", "personality", "perspective", "phenomenon", "philosophy", "photograph", "playground", "politician", "population",
  "possession", "prediction", "preparation", "prescription", "presentation", "prevention", "production", "profession", "pronunciation", "protection",
  "psychology", "publication", "punishment", "quarantine", "reasonable", "recognition", "recommendation", "reflection", "refrigerator", "regulation",
  "relationship", "remarkable", "reputation", "reservation", "resolution", "restaurant", "retirement", "revolution", "satisfaction", "scholarship",
  "screwdriver", "settlement", "significant", "silhouette", "skateboard", "smartphone", "spectacular", "spreadsheet", "springtime", "strawberry",
  "subscription", "suggestion", "supermarket", "supervisor", "suspension", "sweetheart", "technology", "temperature", "temptation", "thermometer",
  "thunderstorm", "tournament", "traditional", "trampoline", "transaction", "transformation", "translation", "transparent", "transportation", "tremendous",
  "typewriter", "ultimately", "underground", "understand", "underwater", "university", "vaccination", "vocabulary", "volleyball", "watermelon",
  "wilderness", "windshield",
];
